window.__ModuleLoader__.load({
  id: "dsh-showcase",
  factory: (require) => {
    const module = { exports: {} };
    const exports = module.exports;
    const React = require("react");
    const { useEffect, useState } = React;

const inject = ["slots", "locale", "connection"];

const RPC_CHANNEL = "/showcase-layout-summary";
const LOCALE_NAMESPACE = "showcase.layoutSummary.settings";
const STYLE_ID = "dsh-showcase-settings-style";

const messages = {
  zh: {
    title: "布局证据海报",
    description: "选择插件每次生成的唯一海报风格。",
    legend: "海报风格",
    field: "边境信号",
    fieldHint: "灰白建筑拼贴、巨型黑字与荧光导视。",
    fish: "蓝色大肥鱼",
    fishHint: "白底角色主视觉、钴蓝冲击字与金色贴纸。",
    saving: "正在保存…",
    saved: "已保存，下一次调用生效。",
    failed: "保存失败，请重试。",
    loading: "正在读取插件设置…",
    unavailable: "插件设置服务当前不可用。",
  },
  en: {
    title: "Layout evidence poster",
    description: "Choose the one poster theme generated by each plugin call.",
    legend: "Poster theme",
    field: "Frontier Signal",
    fieldHint: "Ash-white architectural collage, oversized black type, and fluorescent wayfinding.",
    fish: "Blue Big Fish",
    fishHint: "White character key visual, cobalt impact type, and small gold stickers.",
    saving: "Saving…",
    saved: "Saved. The next tool call will use it.",
    failed: "Could not save the setting. Try again.",
    loading: "Loading plugin settings…",
    unavailable: "Plugin settings are currently unavailable.",
  },
};

const styles = `
.dsh-showcase-settings{list-style:none;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-background-base);overflow:hidden}
.dsh-showcase-settings__head{padding:16px 18px 13px;border-bottom:1px solid var(--dsw-alias-border-l2)}
.dsh-showcase-settings__title{margin:0;color:var(--dsw-alias-label-primary);font-size:14px;font-weight:650}
.dsh-showcase-settings__description{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:1.5}
.dsh-showcase-settings__body{padding:16px 18px 17px}
.dsh-showcase-settings__legend{margin:0 0 10px;color:var(--dsw-alias-label-secondary);font-size:12px;font-weight:600}
.dsh-showcase-settings__choices{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.dsh-showcase-settings__choice{min-height:76px;padding:12px;text-align:left;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-background-elevated);border:1px solid var(--dsw-alias-border-l2);border-radius:6px;cursor:pointer;transition:border-color .16s ease,background-color .16s ease,transform .16s ease}
.dsh-showcase-settings__choice:hover{border-color:var(--dsw-alias-label-tertiary);transform:translateY(-1px)}
.dsh-showcase-settings__choice[aria-checked=true]{border-color:var(--dsw-alias-state-business-primary);background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 10%,var(--dsw-alias-background-elevated))}
.dsh-showcase-settings__choice:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
.dsh-showcase-settings__choice:disabled{cursor:not-allowed;opacity:.58;transform:none}
.dsh-showcase-settings__name{display:block;font-size:13px;font-weight:650}
.dsh-showcase-settings__hint{display:block;margin-top:5px;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:1.45}
.dsh-showcase-settings__status{min-height:18px;margin:9px 0 0;color:var(--dsw-alias-label-tertiary);font-size:11px}
.dsh-showcase-settings__status[data-state=failed]{color:var(--dsw-alias-state-danger-primary)}
@media(max-width:640px){.dsh-showcase-settings__choices{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){.dsh-showcase-settings__choice{transition:none}.dsh-showcase-settings__choice:hover{transform:none}}
`;

function installStyles() {
  if (document.getElementById(STYLE_ID)) return;
  const tag = document.createElement("style");
  tag.id = STYLE_ID;
  tag.textContent = styles;
  document.head.append(tag);
}

function createThemeCard(rpc) {
  return function ThemeCard({ t }) {
    const [theme, setTheme] = useState();
    const [loadState, setLoadState] = useState("loading");
    const [saveState, setSaveState] = useState("idle");
    useEffect(() => {
      let active = true;
      rpc.call(RPC_CHANNEL, "get", {}).then((result) => {
        if (!active) return;
        const value = result.ok ? result.value?.theme : undefined;
        if (value === "frontier-signal" || value === "blue-big-fish") {
          setTheme(value);
          setLoadState("ready");
        } else {
          setLoadState("unavailable");
        }
      }).catch(() => {
        if (active) setLoadState("unavailable");
      });
      return () => {
        active = false;
      };
    }, []);

    if (loadState !== "ready") {
      return React.createElement("li", { className: "dsh-showcase-settings" },
        React.createElement("div", { className: "dsh-showcase-settings__head" },
          React.createElement("h3", { className: "dsh-showcase-settings__title" }, t("title")),
          React.createElement("p", { className: "dsh-showcase-settings__description", role: "status" }, t(loadState))));
    }

    const disabled = saveState === "saving";
    const choose = async (nextTheme) => {
      if (disabled || nextTheme === theme) return;
      setSaveState("saving");
      try {
        const result = await rpc.call(RPC_CHANNEL, "set", { theme: nextTheme });
        const savedTheme = result.ok ? result.value?.theme : undefined;
        if (savedTheme === "frontier-signal" || savedTheme === "blue-big-fish") {
          setTheme(savedTheme);
          setSaveState("saved");
        } else {
          setSaveState("failed");
        }
      } catch {
        setSaveState("failed");
      }
    };

    const choice = (value, nameKey, hintKey) => React.createElement("button", {
      type: "button",
      role: "radio",
      "aria-checked": theme === value,
      className: "dsh-showcase-settings__choice",
      disabled,
      onClick: () => choose(value),
    },
    React.createElement("span", { className: "dsh-showcase-settings__name" }, t(nameKey)),
    React.createElement("span", { className: "dsh-showcase-settings__hint" }, t(hintKey)));

    const status = saveState === "saving"
        ? t("saving")
        : saveState === "saved"
          ? t("saved")
          : saveState === "failed"
            ? t("failed")
            : "";

    return React.createElement("li", { className: "dsh-showcase-settings" },
      React.createElement("div", { className: "dsh-showcase-settings__head" },
        React.createElement("h3", { className: "dsh-showcase-settings__title" }, t("title")),
        React.createElement("p", { className: "dsh-showcase-settings__description" }, t("description"))),
      React.createElement("div", { className: "dsh-showcase-settings__body" },
        React.createElement("p", { className: "dsh-showcase-settings__legend", id: "dsh-showcase-theme-label" }, t("legend")),
        React.createElement("div", { className: "dsh-showcase-settings__choices", role: "radiogroup", "aria-labelledby": "dsh-showcase-theme-label" },
          choice("frontier-signal", "field", "fieldHint"),
          choice("blue-big-fish", "fish", "fishHint")),
        React.createElement("p", { className: "dsh-showcase-settings__status", "data-state": saveState, role: "status" }, status)));
  };
}

function apply(ctx) {
  installStyles();
  ctx.effect(() => ctx.locale.register(LOCALE_NAMESPACE, messages), "dsh-showcase: settings locale");
  const ThemeCard = createThemeCard(ctx.get("connection").rpc);
  ctx.slots.inject("settings.plugin.item", () => ctx.slots.register({
    name: "settings.plugin.item",
    id: "showcase-layout-summary",
    order: 30,
    locale: LOCALE_NAMESPACE,
  }, ThemeCard));
}

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  },
});
